=== jorgeAC97/PracticaMD/build/resources/main/Prueba.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:annotation>
            <xs:documentation xml:lang="es">Esquema que define Lista de colectivos y tarifas de título para sencillos para prolongación de recorrido (SNC) (TLV=B7h)</xs:documentation>
	</xs:annotation>
	<xs:element name="Colectivo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tarifa_Venta_1" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Tarifa_Venta_2" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Tarifa_Venta_3" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
			<xs:attribute name="Codigo" type="xs:string" use="required"/>
			<xs:attribute name="Descripcion" type="xs:string" use="required"/>

		</xs:complexType>
	</xs:element>
	<xs:element name="Empresa_Propietaria_Cod" type="xs:string"/>
	<xs:element name="Empresa_Propietaria_Perfil" type="xs:string"/>
	<xs:element name="Fecha_Cambio_Venta1" type="xs:string"/>
	<xs:element name="Fecha_Cambio_Venta2" type="xs:string"/>
	<xs:element name="Fecha_Fin_Venta" type="xs:string"/>
	<xs:element name="Fecha_Inicio_Venta" type="xs:string"/>
	<xs:element name="Informacion_Tarifas_Titulos">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Titulo" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="TipoTLV" use="required">
				<xs:simpleType>
					<xs:annotation>
						<xs:documentation xml:lang="es">Esta TLV debe tener siempre uno de los valores especificados en la restricción</xs:documentation>
					</xs:annotation>
					<xs:restriction base="xs:string">
						<xs:pattern value="B7|B7h"/>
					</xs:restriction>    
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="Version" use="required">
				<xs:simpleType>
					<xs:annotation>
						<xs:documentation xml:lang="es">El número de version debe ser siempre 3.0</xs:documentation>
					</xs:annotation>
					<xs:restriction base="xs:float">
						<xs:pattern value="1.0"/>
					</xs:restriction>    
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="fecha" type="xs:dateTime" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tarifa_Venta_1">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tipo_Unidades" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Unidades" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tarifa_Venta_2">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tipo_Unidades" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Unidades" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tarifa_Venta_3">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Tipo_Unidades" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Unidades" minOccurs="1" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Tipo_Unidades" type="xs:string"/>
	<xs:element name="Titulo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Empresa_Propietaria_Cod" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Fecha_Inicio_Venta" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Fecha_Cambio_Venta1" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Fecha_Cambio_Venta2" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Fecha_Fin_Venta" minOccurs="1" maxOccurs="1"/>
				<xs:element ref="Colectivo" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="Codigo" type="xs:string" use="required"/>
  		<xs:attribute name="Descripcion" type="xs:string" use="required"/>
  		<xs:attribute name="Zona" type="xs:string" use="required"/>
                </xs:complexType>
	</xs:element>
	<xs:element name="Unidades" type="xs:int"/>
</xs:schema>

=== jorgeAC97/PracticaMD/build/resources/main/Prueba.xml
<?xml version="1.0" encoding="ISO-8859-15"?>
<Informacion_Tarifas_Titulos TipoTLV="B7h" Version="1.0" fecha="2025-02-28T08:07:44" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Prueba.xsd">
 <Titulo Codigo="250Ah" Descripcion="SENCILLO ZONA B2-B3" Zona="00000018h">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Fecha_Inicio_Venta>01/01/2019</Fecha_Inicio_Venta>
  <Fecha_Cambio_Venta1>01/01/2020</Fecha_Cambio_Venta1>
  <Fecha_Cambio_Venta2>19/03/2024</Fecha_Cambio_Venta2>
  <Fecha_Fin_Venta>20/03/2028</Fecha_Fin_Venta>
  <Colectivo Codigo="00h" Descripcion="Normal">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="01h" Descripcion="Discapacidad">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>160</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>160</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>160</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="02h" Descripcion="Familia Numerosa General">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>160</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>160</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>160</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="03h" Descripcion="Familia Numerosa Especial">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>100</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>100</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>100</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="04h" Descripcion="Discapacidad y Familia Numerosa General">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>120</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>120</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>120</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="05h" Descripcion="Discapacidad y Familia Numerosa Especial">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>60</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>60</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>60</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="06h" Descripcion="Incidencia">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>0</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>0</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>0</Unidades>
      </Tarifa_Venta_3>
   </Colectivo>
   <Colectivo Codigo="07h" Descripcion="Gratuito">
        <Tarifa_Venta_1>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>0</Unidades>
        </Tarifa_Venta_1>
        <Tarifa_Venta_2>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>0</Unidades>
        </Tarifa_Venta_2>
        <Tarifa_Venta_3>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>0</Unidades>
        </Tarifa_Venta_3>
   </Colectivo>
   <Colectivo Codigo="08h" Descripcion="Recargo">
        <Tarifa_Venta_1>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>4000</Unidades>
        </Tarifa_Venta_1>
        <Tarifa_Venta_2>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>4000</Unidades>
        </Tarifa_Venta_2>
        <Tarifa_Venta_3>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>4000</Unidades>
        </Tarifa_Venta_3>
  </Colectivo>
 </Titulo>
 <Titulo Codigo="250Bh" Descripcion="SENCILLO ZONA B2-C1" Zona="00000038h">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Fecha_Inicio_Venta>01/01/2019</Fecha_Inicio_Venta>
  <Fecha_Cambio_Venta1>01/01/2020</Fecha_Cambio_Venta1>
  <Fecha_Cambio_Venta2>19/03/2024</Fecha_Cambio_Venta2>
  <Fecha_Fin_Venta>20/03/2028</Fecha_Fin_Venta>
  <Colectivo Codigo="00h" Descripcion="Normal">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>260</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>260</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>260</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="01h" Descripcion="Discapacidad">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="02h" Descripcion="Familia Numerosa General">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>200</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="03h" Descripcion="Familia Numerosa Especial">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>130</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>130</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>130</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="04h" Descripcion="Discapacidad y Familia Numerosa General">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>150</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>150</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>150</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="05h" Descripcion="Discapacidad y Familia Numerosa Especial">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>70</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>70</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>70</Unidades>
      </Tarifa_Venta_3>
  </Colectivo>
  <Colectivo Codigo="06h" Descripcion="Incidencia">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>0</Unidades>
      </Tarifa_Venta_1>
      <Tarifa_Venta_2>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>0</Unidades>
      </Tarifa_Venta_2>
      <Tarifa_Venta_3>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>0</Unidades>
      </Tarifa_Venta_3>
   </Colectivo>
   <Colectivo Codigo="07h" Descripcion="Gratuito">
        <Tarifa_Venta_1>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>0</Unidades>
        </Tarifa_Venta_1>
        <Tarifa_Venta_2>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>0</Unidades>
        </Tarifa_Venta_2>
        <Tarifa_Venta_3>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>0</Unidades>
        </Tarifa_Venta_3>
   </Colectivo>
   <Colectivo Codigo="08h" Descripcion="Recargo">
        <Tarifa_Venta_1>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>4000</Unidades>
        </Tarifa_Venta_1>
        <Tarifa_Venta_2>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>4000</Unidades>
        </Tarifa_Venta_2>
        <Tarifa_Venta_3>
              <Tipo_Unidades>02h</Tipo_Unidades>
              <Unidades>4000</Unidades>
        </Tarifa_Venta_3>
  </Colectivo>
 </Titulo>
 <Titulo Codigo="250Ch" Descripcion="SENCILLO ZONA B2-C2" Zona="00000078h">
  <Empresa_Propietaria_Cod>01h</Empresa_Propietaria_Cod>
  <Fecha_Inicio_Venta>01/01/2019</Fecha_Inicio_Venta>
  <Fecha_Cambio_Venta1>01/01/2020</Fecha_Cambio_Venta1>
  <Fecha_Cambio_Venta2>19/03/2024</Fecha_Cambio_Venta2>
  <Fecha_Fin_Venta>20/03/2028</Fecha_Fin_Venta>
  <Colectivo Codigo="00h" Descripcion="Normal">
      <Tarifa_Venta_1>
            <Tipo_Unidades>02h</Tipo_Unidades>
            <Unidades>360</Unidades>
      </Tarifa_Venta_1>
